apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-operator
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: platform-services/rabbitmq
    repoURL: hhttps://dev.azure.com/{ your organization }/ { your project }/_git/{ your application repo }
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true