apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- controller.yaml

patchesStrategicMerge:
  - p1.yaml



#helmCharts:
#  - name: sealed-secrets
#    releaseName: sealed-secrets
#    repo: https://bitnami-labs.github.io/sealed-secrets
#    namespace: sealed-secrets
#    valuesInline: 
#      containerSecurityContext:
#        runAsNonRoot: true
#        allowPrivilegeEscalation: false
#        seccompProfile:
#          type: RuntimeDefault
#        capabilities:
#          drop: ["ALL"]

