apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops

secretGenerator:
  - name: azurerepo-credentials
    type: Opaque
    
resources:
- argocd-openshiftcluster-creds-sealed.yaml
- argocd-openshiftdemo-creds-sealed.yaml


